config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :posts, only: [:index, :create, :new, :show, :destroy] do
      resources :comments, only: :create 
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :posts

  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :group
belongs_to :user
has_many :comments, dependent: :destroy
has_many :likes, dependent: :destroy
has_many :like_users, through: :likes, source: :user

validates :text, presence: true, unless: :image?

mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  validates :name, presence: true, uniqueness: true

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_group


  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html {  redirect_to request.referer }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end


  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post
  before_action :set_group

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    @post.reload
  end


  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_group
  
  def index
    @posts = @group.posts.includes(:user)
  end

  
  def new 
    @post = Post.new
  end

  def create
    @post = @group.posts.new(post_params)
    if @post.save
      redirect_to group_posts_path(@group), notice: '投稿が完了しました！'
    else
      @posts = @group.posts.includes(:user)
      redirect_to new_group_post_path(@group), alert: 'テキストを入力して下さい'
      
   end
 end

 def destroy
  post = @group.posts.find(params[:id])
  if post.user != current_user
    redirect_to request.referer
  else
    post.destroy
    redirect_to group_posts_path(@group), alert: '投稿を削除しました。'
  end
 end

 def show
  @post = @group.posts.find(params[:id])
  @comment = Comment.new
  @comments = @post.comments.includes(:user)
  @like = Like.new
 end


  private

  def post_params
    params.require(:post).permit(:title, :text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <% if group.errors.any? %>
  <div class="SettingGroupForm__errors">
    <h2>
      <%= "#{group.errors.full_messages.count}件のエラーが発生しました。" %>
    </h2>
    <ul>
      <% group.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="SettingGroupForm__field">
    <div class="SettingGroupForm__leftField">
      <%= f.label :name, "グループ名", class: 'SettingGroupForm__label' %>
    </div>
    <div class="SettingGroupForm__rightField">
      <%= f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください' %>
    </div>
  </div>
  <div class="SettingGroupForm__field">
    <div class="SettingGroupForm__leftField">
      <label class="SettingGroupForm__label">チャットメンバーを追加</label>
    </div>
    <div class="SettingGroupForm__rightField MemberList">
      <%= f.collection_check_boxes :user_ids, User.all, :id, :name %>
    </div>
  </div>
  <div class="SettingGroupForm__field">
    <div class="SettingGroupForm__leftField"></div>
    <div class="SettingGroupForm__rightField">
      <%= f.submit class: 'SettingGroupForm__button GroupButton' %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="SettingGroupForm">
  <h1>チャットグループ編集</h1>
  <%= render partial: 'form', locals: { group: @group } %>
</div>

app/views/groups/index.html.erb
<%= render 'posts/side'%>

app/views/groups/new.html.erb
<div class="SettingGroupForm">
  <h1>新規チャットグループ</h1>
  <%= render partial: 'form', locals: { group: @group } %>
</div>

app/views/layouts/_notifications.html.erb
<div class= "Notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamsCommit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application'%>
  </head>
  <body>
    <% if user_signed_in? %>
    <header>
      <div class= "header">
        <div class= "header-left">
          <%= link_to "TeamsCommit", root_path, class: "app-title" %>
        </div>
      </div>
    </header>
  <% end %>
  <main>
    <div class= "flash-items">
      <%= render 'layouts/notifications' %>
      <%= image_tag "/assets/image3.png", class: "flash-icon"%>
    </div>
    <%= yield %>
  </main>
 </body>
</html>

app/views/likes/_like.html.erb
<%if current_user.already_liked?(post) %>
  <%= button_to group_post_like_path(@group,post,current_user.id), method: :delete, class: "good-icon2 thumbsUp-icon", remote: true do %>
  <p><%= fa_icon("thumbs-up") %></p>
  <%= post.likes.count %>
  <% end %>
<% else %>
  <%= button_to group_post_likes_path(@group,post), class: "good-icon1 thumbsUp-icon", remote:true do %>

    <p><%=fa_icon("thumbs-up") %></p>
    <%= post.likes.count %>
<% end %>
<% end %>

app/views/likes/create.js.erb
$('#like-<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#like-<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_main.html.erb
<div class= "current-group">
  <h2><%= @group.name %></h2>
</div>
<div class= "heder-right">
  <div class= "nav-lists">
    <div class= "nav-icon">
      <%= fa_icon "chevron-circle-down 2x" %>
      </div>
      <ul class= "nav-list">
        <li>
          <%= link_to "投稿",new_group_post_path(@group) , class: "nav-item" %>
        </li>
        <li>
          <%= link_to "グループ編集", edit_group_path(@group), class: "nav-item" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item" %>
        </li>
      </ul>
  </div>
</div>
<div class= "contents">
  <ul class= "content-lists">
    <%= render @posts %>
  </ul>
</div>

app/views/posts/_post.html.erb
<li class= "content-list">
  <%= image_tag post.image.url, class: "content-image"%>
    <div class= "content-date">
      <%= post.created_at.strftime("%m/%d %H時%M分") %>
    </div>
    <%= link_to "<#{post.title.truncate(16)}>", group_post_path(@group, post.id), class: "post-title" %>
      <div class= "content-icon">
       <div id= "like-<%= post.id %>">
        <%= render partial: "likes/like", locals: {post: post}%>
      </div>
        <% if user_signed_in? && current_user.id == post.user_id %>
           <%= link_to fa_icon("trash"), group_post_path(@group, post.id), method: :delete, data:{confirm: "削除しますか？"}, class: "trash-icon"%>
        <% end %>
          <div class= "content-name">
          <%= post.user.name %>
        </div>
    </div>
</li>

app/views/posts/_side.html.erb
<div class= "menu-trigger">
    <span></span>
    <span></span>
    <span></span>
</div>
<div class= "side-bar">
  <div class= "user-name">
      <h2>User Name</h2>
        <div class= "user_edit">
          <p><%= current_user.name %></p>
            <%= link_to fa_icon('cog'), edit_user_path(current_user), class: "side_icon1" %>
        </div>
        </div>
        <% current_user.groups.each do |group| %>
          <%= link_to group_posts_path(group) do %>
            <div class= "group-name">
              <h2><%= group.name %></h2>
            </div>
          <% end %>
        <% end %>
        <%= link_to fa_icon('plus'), new_group_path , class: "side_icon2" %>
  </div>

app/views/posts/index.html.erb
<%= render 'posts/side'%>
<%= render 'posts/main'%>

app/views/posts/new.html.erb
<div class="Form__new">
  <h2>投稿する</h2>
  <%= form_with model: [@group, @post], html: {class: "Form"}, local: true do |f| %>
    <div class="Form__contents">
      <%= f.text_field :title, class: 'Form__inputTitle', placeholder: 'title' %>
      <%= f.text_area :text, class: 'Form__inputText', placeholder: 'text', rows: "14" %>
      <%= f.label :image, class: 'Form__inputImage' do %>
        <%= fa_icon('image 2x', class: 'Form__icon') %>
        <%= f.file_field :image, class: 'Hidden' %>
      <% end %>
    </div>
    <%= f.submit 'Send', class: 'Form__submit' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class= "wrapper">
  <div class= "show-content">
    <div class= "show-list">
       <%= image_tag @post.image.url, class: "show-image"%>
        <%= link_to "<#{@post.title}>", group_post_path(@group, @post.id), class: "show-title" %>
        <div class= "textArea">
          <%= raw Rinku.auto_link(h(@post.text), :all, 'target="_blank"') %>
          </div>
          <div class= "show-icon">
           <div id= "like-<%= @post.id %>">
            <%= render partial: "likes/like", locals: {post: @post}%>
          </div>
            <% if user_signed_in? && current_user.id == @post.user_id %>
              <%= link_to fa_icon("trash"), group_post_path(@group, @post.id), method: :delete, data:{confirm: "削除しますか？"}, class: "trash-icon"%>
            <% end %>
              <div class= "content-name">
              <%= @post.user.name %>
            </div>
            <div class= "show-date">
              <%= @post.created_at.strftime("%m/%d %H時%M分") %>
            </div>
        </div>
     </div>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@group,@post, @comment], local: true, id: "new-comment") do |form| %>
        <%= form.text_field :text, placeholder: "コメントする", rows: "2", class: "comment-text textBox" %>
        <%= form.submit "SEND", class: "comment-button form-submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
           <strong><%=  comment.user.name %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="AccountPage">
  <div class="AccountPage__title">
    <h2>Edit Account</h2>
  </div>
  <div class="AccountPage__form">
    <%= form_for(current_user) do |f| %>
      <div class="FormField">
        <div class="FormField__label--normal">
          <%= f.label :name %>
        </div>
        <div class="FormField__input--normal">
          <%= f.text_field :name, autofocus: true %>
        </div>
      </div>
      <div class="FormField">
        <div class="FormField__label--normal">
          <%= f.label :email %>
        </div>
        <div class="FormField__input--normal">
          <%= f.email_field :email %>
        </div>
      </div>
      <%= f.submit "Update", class: 'Button UserButton' %>
    <% end %>
  </div>
</div>